### ISSUE TITLE
Enhancement: automatische GitHub release van PDF met Travis CI

### ISSUE THREAD

**Issue by jppgks** [MidasLamb/AutomatenEnBerekenbaarheid#1]
zie: https://github.com/jppgks/latex-science-template/blob/master/.travis.yml

**Comment by MidasLamb** [comment]
"This project is a little over-engineered, in the sense that it uses continuous integration to compile a single .pdf file."

**Comment by jppgks** [comment]
"The repository can serve as a template for other (more meaty) LaTeX projects" ;)

**Comment by MidasLamb** [comment]
"uses continuous integration to compile **a single .pdf file.**"
