### ISSUE TITLE
Ontbrekend geval in bewijs niet-regulier zijn van a^{n}b^{n}

### ISSUE THREAD

**Issue by jppgks** [MidasLamb/AutomatenEnBerekenbaarheid#2]
https://github.com/MidasLamb/AutomatenEnBerekenbaarheid/blob/be2e0bce56cacdd5fa29fdcd20c8720bac3e6658/Examenvragen.tex#L44

Hier staat dat er voor iedere opdeling meer a's dan b's zijn. Dit is echter niet het geval, zie p. 44 in de cursus.

**Comment by MidasLamb** [comment]
Aangezien  |xy| <= d, geldt dus dat voor de string a^db^d, xy bestaat uit enkel a's. De cursus maakt geen gebruik van de vereiste dat  |xy| <= d om te bewijzen dat de taal niet regulier is. Dit wel doen maakt het bewijs een stuk eenvoudiger.

**Comment by jppgks** [comment]
Ah nice! 👍
